services:
  pgvector:
    image: pgvector/pgvector:pg18-trixie
    container_name: pgvector
    ports:
      - "5433:5432"
    environment:
      - 'POSTGRES_DB=vectordb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    volumes:
      - pgvector-data:/var/lib/postgresql

  github-mcp:
    image: ghcr.io/github/github-mcp-server:latest
    container_name: github-mcp
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PAT}
    command: ["streamable-http", "--port", "8080", "--host", "0.0.0.0"]

volumes:
  pgvector-data: