spring:
  application:
    name: java-ai-playground

  ai:
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: when_missing
        timeout: 5m
      chat:
        model: mistral
      embedding:
        model: mxbai-embed-large
    vectorstore:
      pgvector:
        initialize-schema: true
    openai:
      api-key: ${OPENAI_API_KEY}
    #mcp.server.enabled: true #only property for mcp server
    mcp:
      client:
        enabled: true
        type: SYNC
        initialized: true
        toolcallback:
          enabled: true
        stdio:
          connections:
            github:
              command: docker
              args: ["run", "-i", "--rm", "-e", "GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PAT}", "ghcr.io/github/github-mcp-server:latest"]

  datasource:
    url: jdbc:postgresql://localhost:5433/vectordb
    username: postgres
    password: postgres

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

langchain4j:
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: mistral
      temperature: 0.0
    embedding-model:
      base-url: http://localhost:11434
      model-name: mxbai-embed-large
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}

logging:
  level:
    dev.langchain4j: DEBUG

routing:
  confidence:
    rag-threshold: 0.85
    max-results: 5